### PR TITLE
return a slice of api.ACLPolicyListEntry for /v1/acl/policies

### LINKED ISSUE #3: /v1/acl/policies needs to return a slice
currently returns a single element

### PR DESCRIPTION
**Pull request by gbolo**
closes #3

### CODE REVIEW

**Comment by mkeeler** [comment]
Thanks for the PR. Could you run:

`mock-api-gen -type Consul -pkg mockconsul -endpoints acl.json -output ./acl.go` to regenerate the acl.go file.

You can install the helper tool like so:

`go get github.com/mkeeler/mock-http-api/cmd/mock-api-gen`

**Comment by mkeeler** [comment]
Perfect. Thanks again.

**Comment by gbolo** [comment]
thanks @mkeeler . it's not an issue that func `NewConsul` was duplicated?

**Comment by mkeeler** [comment]
hmm, your probably right. I will fix that up though.

**Comment by gbolo** [comment]
> hmm, your probably right. I will fix that up though.

thats my bad, I should have spotted it quicker. Was going to remove it but your so quick with the merge ;)

**Comment by mkeeler** [comment]
No worries. I don't know how but the code generator portion and the files in this repo seem to have gotten out of sync. I will probably need to fixup the generator to be able to omit the redeclaration or take multiple endpoint files to generate. Regardless, I fixed it up with another push here now.

**Pull request merged**
